import ThemeProvider from "@/src/components/theme-provider";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import NextTopLoader from "nextjs-toploader";
import { NuqsAdapter } from "nuqs/adapters/next/app";
import "./globals.css";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Tienda",
  description: "Generated by create next app",
  icons: {
    icon: "/icon.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <html lang="es" suppressHydrationWarning>
        <head />
        <body
          className={`${poppins.variable} antialiased`}
          suppressHydrationWarning
        >
          <NextTopLoader
            color="#2563eb"
            height={4}
            showAtBottom={true}
            shadow={false}
          />
          <ThemeProvider
            attribute="class"
            defaultTheme="light"
            enableSystem
            disableTransitionOnChange={false}
          >
            <NuqsAdapter>{children}</NuqsAdapter>
          </ThemeProvider>
        </body>
      </html>
    </>
  );
}
